language: python
python:
  - "2.7"
env:
  matrix:
    - TOX_ENV=coverage
    - TOX_ENV=flake8
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
cache:
  directories:
    - $HOME/.cache/pip/
    - $HOME/build/nitmir/django-cas-server/.tox/
install:
  - "travis_retry pip install setuptools --upgrade"
  - "pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
