language: python
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=flake8
  - python: "2.7"
    env: TOX_ENV=check_rst
  - python: "2.7"
    env: TOX_ENV=py27-django17
  - python: "2.7"
    env: TOX_ENV=py27-django18
  - python: "2.7"
    env: TOX_ENV=py27-django19
  - python: "2.7"
    env: TOX_ENV=py27-django110
  - python: "3.4"
    env: TOX_ENV=py34-django17
  - python: "3.4"
    env: TOX_ENV=py34-django18
  - python: "3.4"
    env: TOX_ENV=py34-django19
  - python: "3.4"
    env: TOX_ENV=py34-django110
  - python: "3.5"
    env: TOX_ENV=py35-django18
  - python: "3.5"
    env: TOX_ENV=py35-django19
  - python: "3.5"
    env: TOX_ENV=py35-django110
  - python: "2.7"
    env: TOX_ENV=coverage
cache:
  directories:
    - $HOME/.cache/pip/http/
    - $HOME/build/nitmir/django-cas-server/.tox/$TOX_ENV/
install:
  - "travis_retry pip install setuptools --upgrade"
  - "pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat tox_log/*.log
